### ISSUE TITLE
splinter_test --functionality 1000000000 (1 billion inserts) runs into seg-fault. And Assertion in Debug mode run.

### ISSUE THREAD

**Issue by gapisback** [vmware/splinterdb#311]
A big run of in optimized mode of following test failed with seg-fault. This is on /main @ SHA 916625a

`$ ./bin/driver_test/splinter_test --functionality 1000000000 1000 --num-tables 2 --cache-per-table`

Rebuild DEBUG binary and ran this under the debugger. It ran for a while and then failed like so:

```
Round i=    2288, op= 0, nummsgs =      306, minkey= 1913649, maxkey=16954161, mindelta =     16384, maxdelta=    81920
Round i=    2289, op= 1, nummsgs =       81, minkey=14321261, maxkey=18518157, mindelta =   4194304, maxdelta=  4194368
Round i=    2290, op= 0, nummsgs =        1, minkey= 2902164, maxkey= 2903188, mindelta =       512, maxdelta=     1536
Round i=    2291, op= 0, nummsgs =        1, minkey= 4959638, maxkey= 4959662, mindelta =        16, maxdelta=       32
Round i=    2292, op= 0, nummsgs =   488309, minkey= 1010561, maxkey=13798977, mindelta =       -64, maxdelta=  4194240
Assertion failed at src/trunk.c:6141:trunk_async_callback(): "ctxt->state == async_state_get_child_trunk_node_reentrant".

Program received signal SIGABRT, Aborted.
```

The stack looks like follows:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d12859 in __GI_abort () at abort.c:79
#2  0x00007ffff7fa681e in platform_assert_false (stream=0x7ffff7ed95c0 <_IO_2_1_stderr_>, filename=0x7ffff7fb0284 "src/trunk.c",
    linenumber=6141, functionname=0x7ffff7fb4060 <__FUNCTION__.10414> "trunk_async_callback",
    expr=0x7ffff7fb1508 "ctxt->state == async_state_get_child_trunk_node_reentrant", message=0x7ffff7fafca0 "")
    at src/platform_linux/platform.c:328
#3  0x00007ffff7f8f296 in trunk_async_callback (cache_ctxt=0x5555555b7f00) at src/trunk.c:6141
#4  0x00007ffff7f74ca7 in clockcache_read_async_callback (metadata=0x7ffff7b78e70, iovec=0x7ffff7b78ed0, count=1, status=...)
    at src/clockcache.c:2331
#5  0x00007ffff7fa5880 in laio_callback (ctx=0x7ffff7b8b000, iocb=0x7ffff7b78e20, res=4096, res2=0) at src/platform_linux/laio.c:220
#6  0x00007ffff7fa5b97 in laio_cleanup (ioh=0x55555559a200, count=0) at src/platform_linux/laio.c:293
#7  0x00007ffff7fa4e9e in io_cleanup (io=0x55555559a200, count=0) at src/io.h:147
#8  0x00007ffff7fa598d in laio_read_async (ioh=0x55555559a200, req=0x7ffff7b78e20, callback=0x7ffff7f74a4d <clockcache_read_async_callback>,
    count=1, addr=6553600) at src/platform_linux/laio.c:243
#9  0x00007ffff7f7067a in io_read_async (io=0x55555559a200, req=0x7ffff7b78e20, callback=0x7ffff7f74a4d <clockcache_read_async_callback>,
    count=1, addr=6553600) at src/io.h:131
#10 0x00007ffff7f750fd in clockcache_get_async (cc=0x5555555a4140, addr=6553600, type=PAGE_TYPE_FIRST, ctxt=0x5555555b7f00)
    at src/clockcache.c:2480
#11 0x00007ffff7f70e59 in clockcache_get_async_virtual (c=0x5555555a4140, addr=6553600, type=PAGE_TYPE_FIRST, ctxt=0x5555555b7f00)
    at src/clockcache.c:387
#12 0x00007ffff7f7c2ad in cache_get_async (cc=0x5555555a4140, addr=6553600, type=PAGE_TYPE_FIRST, ctxt=0x5555555b7f00) at src/cache.h:275
#13 0x00007ffff7f7ece7 in trunk_node_get_async (spl=0x7fecd24ef040, addr=6553600, ctxt=0x5555555b7e58) at src/trunk.c:939
#14 0x00007ffff7f8f5c6 in trunk_lookup_async (spl=0x7fecd24ef040, key=0x5555555b7f48 "", data=0x5555555b7f60, ctxt=0x5555555b7e58)
    at src/trunk.c:6266
#15 0x000055555558235a in async_ctxt_process_one (spl=0x7fecd24ef040, async_lookup=0x5555555b43c0, ctxt=0x5555555b7e58, latency_max=0x0,
    process_cb=0x55555556c055 <verify_tuple_callback>, process_arg=0x7fffffffdffc) at tests/functional/test_async.c:126
#16 0x000055555556c336 in verify_against_shadow (spl=0x7fecd24ef040, keybuf=0x555555c084c0 "", sharr=0x7fffffffe100,
    async_lookup=0x5555555b43c0) at tests/functional/test_functionality.c:148
#17 0x000055555556d057 in validate_tree_against_shadow (spl=0x7fecd24ef040, prg=0x7fffffffe280, keybuf=0x555555c084c0 "",
    shadow=0x5555555b95c0, hh=0x0, hid=0x0, do_it=0, async_lookup=0x5555555b43c0) at tests/functional/test_functionality.c:479
#18 0x000055555556e08e in test_functionality (al=0x7fffffffe430, io=0x55555559a200, cc=0x55555559a880, cfg=0x555555599a80, seed=0,
    num_inserts=1000000000, correctness_check_frequency=1000, state=0x7ffff7a69040, hh=0x0, hid=0x0, num_tables=2 '\002',
    num_caches=2 '\002', max_async_inflight=64) at tests/functional/test_functionality.c:781
#19 0x0000555555568810 in splinter_test (argc=7, argv=0x7fffffffe7e0) at tests/functional/splinter_test.c:2570
#20 0x000055555557700e in test_dispatcher (argc=8, argv=0x7fffffffe7d8) at tests/functional/test_dispatcher.c:41
#21 0x0000555555575f25 in main (argc=8, argv=0x7fffffffe7d8) at tests/functional/driver_test.c:13
```

Problem is reproducible, but takes about 30+ mins to get there.

---
For what it's worth, `$ driver_test/splinter_test --functionality 100000000 1000 --num-tables 2 --cache-per-table` succeeded with 100 Mil inserts, and all num_inserts less than that. 

I just cranked it up to 1 billion to see how far we can go.

**Comment by rtjohnso** [comment]
This now works with async, as well.
