### ISSUE TITLE
splinter_test run with large'ish memtable [--memtable-capacity-gib 12] runs into signal in routing_filter_add()

### ISSUE THREAD

**Issue by gapisback** [vmware/splinterdb#344]
Following simple execution of `splinter_test` trips up a seg-fault.

```
Fusion-LocalVM:[161] $ bin/driver_test splinter_test --functionality 1000000 100 --page-size 4096 --memtable-capacity-gib 12
bin/driver_test: splinterdb_build_version f60f2df3
Dispatch test splinter_test
Fingerprint size 36 too large, max value size is 5, setting to 27
fingerprint_size: 27
[...]
Round i=      16, op= 2, nummsgs =   495646, minkey=33378992, maxkey=66437778, mindelta = -16777216, maxdelta=-16777215
Round i=      17, op= 0, nummsgs =      568, minkey=32418244, maxkey=32495492, mindelta =         8, maxdelta=      264
Segmentation fault (core dumped)
```

Discovered through manual testing on /main @ SHA f60f2df. The machine has 15 GiB of RAM, so this usage should have been a legitimate one.

**With release build, the stack under the debugger looks like:**

```
Round i=      16, op= 2, nummsgs =   495646, minkey=33378992, maxkey=66437778, mindelta = -16777216, maxdelta=-16777215
Round i=      17, op= 0, nummsgs =      568, minkey=32418244, maxkey=32495492, mindelta =         8, maxdelta=      264

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d689c2 in routing_filter_add (cc=<optimized out>, cfg=<optimized out>, hid=<optimized out>, old_filter=<optimized out>, filter=<optimized out>,
    new_fp_arr=<optimized out>, num_new_fp=<optimized out>, value=<optimized out>) at src/routing_filter.c:568
568	            dst_fp[fps_added++] = fp & remainder_and_value_mask;
(gdb) bt
#0  0x00007ffff7d689c2 in routing_filter_add (cc=<optimized out>, cfg=<optimized out>, hid=<optimized out>, old_filter=<optimized out>, filter=<optimized out>,
    new_fp_arr=<optimized out>, num_new_fp=<optimized out>, value=<optimized out>) at src/routing_filter.c:568
#1  0x00007ffff7d7b6e2 in trunk_build_filters (req=0x5555555c9600, spl=0x7fffb2ef0040) at src/trunk.c:3551
#2  trunk_bundle_build_filters (arg=<optimized out>, scratch=<optimized out>) at src/trunk.c:3683
#3  0x00007ffff7d7545c in task_group_perform_one (group=group@entry=0x7ffff7ae8540) at src/task.c:551
#4  0x00007ffff7d756df in task_perform_one (ts=ts@entry=0x7ffff7ae7040) at src/task.c:576
#5  0x00007ffff7d757fd in task_perform_all (ts=0x7ffff7ae7040) at src/task.c:480
#6  0x00007ffff7d6e8b4 in trunk_prepare_for_shutdown (spl=spl@entry=0x7fffb2ef0040) at src/trunk.c:6935
#7  0x00007ffff7d6ea21 in trunk_destroy (spl=0x7fffb2ef0040) at src/trunk.c:7013
#8  0x000055555556f7bc in test_functionality (io=<optimized out>, max_async_inflight=<optimized out>, num_caches=1 '\001', num_tables=<optimized out>, hid=0x0,
    hh=0x0, state=<optimized out>, correctness_check_frequency=100, num_inserts=1000000, seed=<optimized out>, cfg=0x555555583940, cc=0x555555584700,
    al=0x7fffffffe4a0) at tests/functional/splinter_test.c:2317
#9  splinter_test (argc=<optimized out>, argv=<optimized out>) at tests/functional/splinter_test.c:2575
#10 0x00007ffff7df60b3 in __libc_start_main (main=0x555555557ea0 <main>, argc=9, argv=0x7fffffffe818, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe808) at ../csu/libc-start.c:308
#11 0x00005555555580de in _start ()
(gdb) quit
```

**Under the debugger**, w/ DEBUG build the stack looks like below, slightly different -- **reporting an assertion**:

```
Round i=      17, op= 0, nummsgs =      568, minkey=32418244, maxkey=32495492, mindelta =         8, maxdelta=      264
Assertion failed at src/routing_filter.c:608:routing_filter_add(): "bytes_remaining_on_page >= header_size + remainder_block_size".

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d12859 in __GI_abort () at abort.c:79
#2  0x00007ffff7fa6bfa in platform_assert_false (stream=0x7ffff7ed95c0 <_IO_2_1_stderr_>, filename=0x7ffff7fb508d "src/routing_filter.c", linenumber=608,
    functionname=0x7ffff7fb5690 <__FUNCTION__.10452> "routing_filter_add", expr=0x7ffff7fb5310 "bytes_remaining_on_page >= header_size + remainder_block_size",
    message=0x7ffff7fb5000 "") at src/platform_linux/platform.c:328
#3  0x00007ffff7fa0a93 in routing_filter_add (cc=0x55555559c040, cfg=0x7fffb2d5a0f8, hid=0x0, old_filter=0x7fffffffdbe0, filter=0x7fffb2dab2c0,
    new_fp_arr=0x7ffeec61f040, num_new_fp=982440, value=0) at src/routing_filter.c:608
#4  0x00007ffff7f848ef in trunk_memtable_compact_and_build_filter (spl=0x7fffb2d5a040, generation=0, tid=0) at src/trunk.c:3004
#5  0x00007ffff7f8563a in trunk_memtable_flush_internal (spl=0x7fffb2d5a040, generation=0) at src/trunk.c:3248
#6  0x00007ffff7f856c0 in trunk_memtable_flush_internal_virtual (arg=0x7fffb2dab2e8, scratch=0x7ffff7953828) at src/trunk.c:3266
#7  0x00007ffff7f7b192 in task_group_perform_one (group=0x7ffff7951280) at src/task.c:551
#8  0x00007ffff7f7b30a in task_perform_one (ts=0x7ffff7951040) at src/task.c:576
#9  0x00007ffff7f7acd1 in task_perform_all (ts=0x7ffff7951040) at src/task.c:480
#10 0x00007ffff7f91b24 in trunk_prepare_for_shutdown (spl=0x7fffb2d5a040) at src/trunk.c:6935
#11 0x00007ffff7f91e59 in trunk_destroy (spl=0x7fffb2d5a040) at src/trunk.c:7013
#12 0x000055555556e555 in test_functionality (al=0x7fffffffe470, io=0x55555559a200, cc=0x55555559a700, cfg=0x555555599940, seed=0, num_inserts=1000000,
    correctness_check_frequency=100, state=0x7ffff7951040, hh=0x0, hid=0x0, num_tables=1 '\001', num_caches=1 '\001', max_async_inflight=64)
    at tests/functional/test_functionality.c:861
#13 0x0000555555568858 in splinter_test (argc=8, argv=0x7fffffffe820) at tests/functional/splinter_test.c:2575
#14 0x00005555555770ba in test_dispatcher (argc=9, argv=0x7fffffffe818) at tests/functional/test_dispatcher.c:41
#15 0x0000555555575fd1 in main (argc=9, argv=0x7fffffffe818) at tests/functional/driver_test.c:13
```

**Comment by rtjohnso** [comment]
These all appear to work now.
