### ISSUE TITLE
Suspected code error in splinterdb_iterator_init(), results in seg-fault and / or unpredictable behaviour in iterator init() logic

### ISSUE THREAD

**Issue by gapisback** [vmware/splinterdb#419]
### Describe the bug

This issue was discovered while developing C-sample programs under PR #399. An attempt was made to extract out a stand-alone repro with a test-case.

The following simple test case results in an assertion failure from `trunk_range_iterator_init()` -> `trunk_find_pivot()`.

The test is simply doing very basic configuration of SplinterDB, then `splinterdb_create()`, followed by `splinterdb_iterator_init`. Stack is as follows:

```
#2  0x00007ffff7fa3645 in platform_assert_false (filename=0x7ffff7fad9db "src/trunk.c",
    linenumber=1373, functionname=0x7ffff7fb1ab0 <__FUNCTION__.9172> "trunk_find_pivot",
    expr=0x7ffff7fadbb2 "cmp <= 0", message=0x7ffff7fad3aa "")
    at src/platform_linux/platform.c:335
335	   abort();
(gdb)
#3  0x00007ffff7f79c5b in trunk_find_pivot (spl=0x5555558082c0, node=0x5555557a8e80,
    key=0x555555dc0f88 "", comp=less_than_or_equal) at src/trunk.c:1373
1373	            debug_assert(cmp <= 0);
(gdb)
#4  0x00007ffff7f88da2 in trunk_range_iterator_init (spl=0x5555558082c0,
    range_itor=0x555555dc0b40, min_key=0x7fffffffe590 "", max_key=0x0,
    num_tuples=18446744073709551615) at src/trunk.c:5768
5768	         trunk_find_pivot(spl, node, range_itor->min_key, less_than_or_equal);
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d0b859 in __GI_abort () at abort.c:79
#2  0x00007ffff7fa3645 in platform_assert_false (filename=0x7ffff7fad9db "src/trunk.c",
    linenumber=1373, functionname=0x7ffff7fb1ab0 <__FUNCTION__.9172> "trunk_find_pivot",
    expr=0x7ffff7fadbb2 "cmp <= 0", message=0x7ffff7fad3aa "")
    at src/platform_linux/platform.c:335
#3  0x00007ffff7f79c5b in trunk_find_pivot (spl=0x5555558082c0, node=0x5555557a8e80,
    key=0x555555dc0f88 "", comp=less_than_or_equal) at src/trunk.c:1373
#4  0x00007ffff7f88da2 in trunk_range_iterator_init (spl=0x5555558082c0,
    range_itor=0x555555dc0b40, min_key=0x7fffffffe590 "", max_key=0x0,
    num_tuples=18446744073709551615) at src/trunk.c:5768
#5  0x00007ffff7f66e7a in splinterdb_iterator_init (kvs=0x55555557c040, iter=0x7fffffffe640,
    start_key=...) at src/splinterdb.c:822
#6  0x000055555555c66d in ctest_splinterdb_quick_test_custom_cmp_iterator_init_bug_run (
    data=0x55555556de80 <ctest_splinterdb_quick_test_custom_cmp_iterator_init_bug_data>)
    at tests/unit/splinterdb_quick_test.c:847
```

The code fragment where this fails is this:

```
1350 static inline uint16
1351 trunk_find_pivot(trunk_handle *spl,
[...]
1366    if (size == 1) {
1367       cmp = trunk_key_compare(spl, trunk_get_pivot(spl, node, 0), key);
1368       switch (comp) {
1369          case less_than:
1370             debug_assert(cmp < 0);
1371             return 0;
1372          case less_than_or_equal:
1373             debug_assert(cmp <= 0);
1374             return 0;
```

Under the debugger we find: 
```
(gdb) p cmp
$1 = 24
```

### Reproduction steps

```bash
1. Unit-test being developed: Something on the lines of:

CTEST2(splinterdb_quick, test_custom_cmp_iterator_init_bug)
{
   // We need to reconfigure Splinter with user-specified data_config
   // Tear down default instance, and create a new one.
   splinterdb_close(&data->kvsb);
   data->cfg.data_cfg                 = test_data_config;

   // Assert will trip if you enable this set.
   data->cfg.data_cfg->key_size       = 24;
   data->cfg.data_cfg->min_key_length = 24;
   data->cfg.data_cfg->max_key_length = 24;

   int rc = splinterdb_create(&data->cfg, &data->kvsb);
   ASSERT_EQUAL(0, rc);

   const int num_inserts = 5;
   rc = insert_some_keys(num_inserts, data->kvsb);
   ASSERT_EQUAL(0, rc);

   splinterdb_iterator *it = NULL;
   rc = splinterdb_iterator_init(data->kvsb, &it, NULL_SLICE);
   ASSERT_EQUAL(0, rc);

   bool iter_valid = splinterdb_iterator_valid(it);
   ASSERT_TRUE(iter_valid);
```

### Expected behavior

- Should not get any assertions
-  Even with attempted fix in `splinterdb_iterator_init` to correct the handling of on-stack `start_key_buffer` , the assertion in the unit-test on `iter_valid` trips unexpectedly. Iterator comes up as "invalid" whereas it should have been "valid"
- Under development unit-test should pass cleanly for all combinations.

**Comment by gapisback** [comment]
Fixed by this commit:

```
c3e6952 gapisback 24 minutes ago Thu, 09-Jun-2022, 05:51:32 PM (Authored: Thu, 09-Jun-2022, 05:51:32 PM)
 (#419) Fix bug in splinterdb_iterator_init() when min_key is configured.
```
